import React, { useState } from 'react';
import { generateImage } from '../services/geminiService';
import { AspectRatio, ImageFile } from '../types';
import { ASPECT_RATIOS } from '../constants';
import { ArrowRightOnRectangleIcon, LoadingSpinner, SparklesIcon } from './icons';
import { base64ToImageFile } from '../utils/fileUtils';

interface ImageStudioProps {
    onSelectObjectForRedesign: (imageFile: ImageFile) => void;
}

export const ImageStudio: React.FC<ImageStudioProps> = ({ onSelectObjectForRedesign }) => {
    const [prompt, setPrompt] = useState('');
    const [aspectRatio, setAspectRatio] = useState<AspectRatio>(AspectRatio.SQUARE);
    const [generatedImage, setGeneratedImage] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [isSending, setIsSending] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleGenerate = async () => {
        if (!prompt) {
            setError('Please enter a prompt.');
            return;
        }
        setIsLoading(true);
        setError(null);
        setGeneratedImage(null);

        try {
            const imageBase64 = await generateImage(prompt, aspectRatio);
            setGeneratedImage(`data:image/jpeg;base64,${imageBase64}`);
        } catch (e) {
            setError(e instanceof Error ? e.message : 'An unknown error occurred.');
        } finally {
            setIsLoading(false);
        }
    };

    const handleUseForInpainting = async () => {
        if (!generatedImage) return;
        setIsSending(true);
        try {
            const imageFile = await base64ToImageFile(generatedImage, 'generated-object.jpeg');
            onSelectObjectForRedesign(imageFile);
        } catch (e) {
            setError('Failed to prepare image for redesigner.');
        } finally {
            setIsSending(false);
        }
    };


    return (
        <div className="p-4 md:p-6 h-full flex flex-col gap-6">
            <div className="bg-white dark:bg-gray-800 p-6 rounded-2xl shadow-lg">
                <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-4">Image Studio</h2>
                <div className="flex flex-col md:flex-row gap-4">
                    <input
                        type="text"
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        placeholder="e.g., A futuristic armchair, minimalist living room"
                        className="flex-grow p-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-800 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    />
                     <select
                        value={aspectRatio}
                        onChange={(e) => setAspectRatio(e.target.value as AspectRatio)}
                        className="p-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-800 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    >
                        {ASPECT_RATIOS.map(ratio => (
                            <option key={ratio.value} value={ratio.value}>{ratio.label}</option>
                        ))}
                    </select>
                    <button
                        onClick={handleGenerate}
                        disabled={isLoading}
                        className="flex items-center justify-center gap-2 bg-blue-600 text-white font-bold py-3 px-6 rounded-lg hover:bg-blue-700 disabled:bg-gray-400 transition-colors shadow-lg"
                    >
                        {isLoading ? <LoadingSpinner/> : <SparklesIcon className="w-6 h-6" />}
                        Generate
                    </button>
                </div>
                 {error && <p className="text-red-500 text-sm mt-2">{error}</p>}
            </div>

            <div className="flex-grow bg-white dark:bg-gray-800 p-6 rounded-2xl shadow-lg flex items-center justify-center">
                <div className="w-full h-full bg-gray-100 dark:bg-gray-700 rounded-lg flex items-center justify-center">
                    {isLoading && <LoadingSpinner />}
                    {!isLoading && generatedImage && (
                        <div className="relative w-full h-full flex items-center justify-center">
                            <img src={generatedImage} alt="Generated by AI" className="max-w-full max-h-full object-contain rounded-lg" />
                            <div className="absolute bottom-4 right-4">
                                <button
                                    onClick={handleUseForInpainting}
                                    disabled={isSending}
                                    className="flex items-center gap-2 bg-green-600 text-white font-bold py-2 px-4 rounded-lg hover:bg-green-700 disabled:bg-gray-400 transition-all duration-200 shadow-lg"
                                >
                                    {isSending ? <LoadingSpinner/> : <ArrowRightOnRectangleIcon className="w-5 h-5" />}
                                    Use for Inpainting
                                </button>
                            </div>
                        </div>
                    )}
                    {!isLoading && !generatedImage && (
                        <p className="text-gray-500">Your generated image will appear here</p>
                    )}
                </div>
            </div>
        </div>
    );
};